### ISSUE TITLE
关于架构问题

### ISSUE THREAD

**Issue by quinn0809** [lmf12/SimpleCam#1]
一直在关注这个项目，有个问题，你通过分类的形式对UIViewController进行瘦身，这种方式很新颖，能否谈谈你的理解呢？微信:fengpingguohaha

**Comment by lmf12** [comment]
@quinn0809 这种方式在 [《Effective Objective-C 2.0》](https://book.douban.com/subject/25829244/) 这本书的第 24 条有介绍到。个人感觉这种按照功能模块来划分分类的方式，能够在一定程度上降低各功能的耦合度。在添加新的模块（加多一个分类），或者删除一个旧模块（直接删掉分类）时，也会方便不少。

**Comment by bmarkinominjie** [comment]
1.闪光灯的问题，你这项目默认的是开启前置摄相头，应该不需要闪光灯的，应该可以开启前置摄相关时，关闭闪光灯选项
2.切换前后摄相头模块好像有bug，不能切换成功，我用iphoneX试了一下抖音的切换功能，好像也是有问题的，你可以看一下

**Comment by lmf12** [comment]
@bmarkinominjie 谢谢反馈。

1. 前置禁用闪光灯这个，后续可以考虑做个 UI 上禁止点击的优化。
2. 不能切换成功的问题，可以描述清楚一些吗？比如说是一直不成功，还是某些情况不成功；抖音切换有问题，具体是什么问题呢？（有截图或视频更好）因为我这边貌似是没问题的。😂

**Comment by bmarkinominjie** [comment]
我用的是你的0.1版本，我的手机是iPhoneX ,系统版本是13.1.3，应用启动后默认开启的是前置摄相头，直接切换后置摄相头所有界面卡死,不能交互，播放图层停留在前置摄相头的最后一帧，过几秒后交互恢复，播放图层依然停留在前置摄相头的最后一帧，切换成前置摄相头又没事了。本想用最新版本的，但项目里的openCV pod不下来,我的另一个手机iphone6 ,系统版本是9.1是正常的，没有问题。

**Comment by bmarkinominjie** [comment]
抖音iPhoneX ,系统版本是13.1.3也是有问题的，我的另一个手机iphone6 ,系统版本是9.1正常。

**Comment by lmf12** [comment]
@bmarkinominjie 我手上有台 iPhone 11  iOS 13.1.2 的设备，好像也没有出现你的情况。这个问题后面我有时间再看看吧。openCV 这个确实比较坑，效果不好，库还比较大，后续考虑删掉好了。

**Comment by bmarkinominjie** [comment]
应该就是那个特定版本问题，13.1.3版本会出现，我刚把手机升级成13.2.2后，就不再出现这个问题了

**Comment by bmarkinominjie** [comment]
抖音升级版本问题后也不再出现这个问题了
