### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by linhongmin1027** [lmf12/SimpleCam#3]
iOS13 iphone7 运行报这个warning

Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 11292, TID: 2714676, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   SimpleCam                           0x0000000102e9a1d4 __39-[GPUImageView recalculateViewGeometry]_block_invoke + 56
5   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
6   SimpleCam                           0x0000000102e9a17c -[GPUImageView recalculateViewGeometry] + 108
7   SimpleCam                           0x0000000102e9ab78 __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 312
8   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
9   SimpleCam                           0x0000000102e9aa20 -[GPUImageView setInputSize:atIndex:] + 136
10  SimpleCam                           0x0000000102e4cd5c -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 748
11  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
12  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
13  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
14  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
15  SimpleCam                           0x0000000102e48a70 -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 152
16  SimpleCam                           0x0000000102e96590 -[GPUImageVideoCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1716
17  SimpleCam                           0x0000000102e96e9c -[GPUImageVideoCamera processVideoSampleBuffer:] + 2124
18  SimpleCam                           0x0000000102e97a58 __74-[GPUImageVideoCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke + 176
19  libdispatch.dylib                   0x0000000103c217fc _dispatch_call_block_and_release + 24
20  libdispatch.dylib                   0x0000000103c22bd8 _dispatch_client_callout + 16
21  libdispatch.dylib                   0x0000000103c29b48 _dispatch_lane_serial_drain + 744
22  libdispatch.dylib                   0x0000000103c2a6e4 _dispatch_lane_invoke + 448
23  libdispatch.dylib                   0x0000000103c35adc _dispatch_workloop_worker_thread + 1324
24  libsystem_pthread.dylib             0x00000001b4d4af88 _pthread_wqthread + 276
25  libsystem_pthread.dylib             0x00000001b4d4dad4 start_wqthread + 8
2020-01-07 15:04:15.420197+0800 SimpleCam[11292:2714676] [reports] Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 11292, TID: 2714676, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   SimpleCam                           0x0000000102e9a1d4 __39-[GPUImageView recalculateViewGeometry]_block_invoke + 56
5   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
6   SimpleCam                           0x0000000102e9a17c -[GPUImageView recalculateViewGeometry] + 108
7   SimpleCam                           0x0000000102e9ab78 __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 312
8   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
9   SimpleCam                           0x0000000102e9aa20 -[GPUImageView setInputSize:atIndex:] + 136
10  SimpleCam                           0x0000000102e4cd5c -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 748
11  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
12  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
13  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
14  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
15  SimpleCam                           0x0000000102e48a70 -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 152
16  SimpleCam                           0x0000000102e96590 -[GPUImageVideoCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1716
17  SimpleCam                           0x0000000102e96e9c -[GPUImageVideoCamera processVideoSampleBuffer:] + 2124
18  SimpleCam                           0x0000000102e97a58 __74-[GPUImageVideoCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke + 176
19  libdispatch.dylib                   0x0000000103c217fc _dispatch_call_block_and_release + 24
20  libdispatch.dylib                   0x0000000103c22bd8 _dispatch_client_callout + 16
21  libdispatch.dylib                   0x0000000103c29b48 _dispatch_lane_serial_drain + 744
22  libdispatch.dylib                   0x0000000103c2a6e4 _dispatch_lane_invoke + 448
23  libdispatch.dylib                   0x0000000103c35adc _dispatch_workloop_worker_thread + 1324
24  libsystem_pthread.dylib             0x00000001b4d4af88 _pthread_wqthread + 276
25  libsystem_pthread.dylib             0x00000001b4d4dad4 start_wqthread + 8
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView layer]
PID: 11292, TID: 2714676, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   SimpleCam                           0x0000000102e99bf0 -[GPUImageView createDisplayFramebuffer] + 288
5   SimpleCam                           0x0000000102e9a018 -[GPUImageView setDisplayFramebuffer] + 72
6   SimpleCam                           0x0000000102e9a664 __44-[GPUImageView newFrameReadyAtTime:atIndex:]_block_invoke + 112
7   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
8   SimpleCam                           0x0000000102e9a5d4 -[GPUImageView newFrameReadyAtTime:atIndex:] + 116
9   SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
10  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
11  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
12  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
13  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
14  SimpleCam                           0x0000000102e48a70 -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 152
15  SimpleCam                           0x0000000102e96590 -[GPUImageVideoCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1716
16  SimpleCam                           0x0000000102e96e9c -[GPUImageVideoCamera processVideoSampleBuffer:] + 2124
17  SimpleCam                           0x0000000102e97a58 __74-[GPUImageVideoCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke + 176
18  libdispatch.dylib                   0x0000000103c217fc _dispatch_call_block_and_release + 24
19  libdispatch.dylib                   0x0000000103c22bd8 _dispatch_client_callout + 16
20  libdispatch.dylib                   0x0000000103c29b48 _dispatch_lane_serial_drain + 744
21  libdispatch.dylib                   0x0000000103c2a6e4 _dispatch_lane_invoke + 448
22  libdispatch.dylib                   0x0000000103c35adc _dispatch_workloop_worker_thread + 1324
23  libsystem_pthread.dylib             0x00000001b4d4af88 _pthread_wqthread + 276
24  libsystem_pthread.dylib             0x00000001b4d4dad4 start_wqthread + 8
2020-01-07 15:04:26.491685+0800 SimpleCam[11292:2714676] [reports] Main Thread Checker: UI API called on a background thread: -[UIView layer]
PID: 11292, TID: 2714676, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   SimpleCam                           0x0000000102e99bf0 -[GPUImageView createDisplayFramebuffer] + 288
5   SimpleCam                           0x0000000102e9a018 -[GPUImageView setDisplayFramebuffer] + 72
6   SimpleCam                           0x0000000102e9a664 __44-[GPUImageView newFrameReadyAtTime:atIndex:]_block_invoke + 112
7   SimpleCam                           0x0000000102e738c8 runSynchronouslyOnVideoProcessingQueue + 104
8   SimpleCam                           0x0000000102e9a5d4 -[GPUImageView newFrameReadyAtTime:atIndex:] + 116
9   SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
10  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
11  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
12  SimpleCam                           0x0000000102e4ed94 -[GPUImageFilter newFrameReadyAtTime:atIndex:] + 216
13  SimpleCam                           0x0000000102e4d048 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 1496
14  SimpleCam                           0x0000000102e48a70 -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 152
15  SimpleCam                           0x0000000102e96590 -[GPUImageVideoCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1716
16  SimpleCam                           0x0000000102e96e9c -[GPUImageVideoCamera processVideoSampleBuffer:] + 2124
17  SimpleCam                           0x0000000102e97a58 __74-[GPUImageVideoCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke + 176
18  libdispatch.dylib                   0x0000000103c217fc _dispatch_call_block_and_release + 24
19  libdispatch.dylib                   0x0000000103c22bd8 _dispatch_client_callout + 16
20  libdispatch.dylib                   0x0000000103c29b48 _dispatch_lane_serial_drain + 744
21  libdispatch.dylib                   0x0000000103c2a6e4 _dispatch_lane_invoke + 448
22  libdispatch.dylib                   0x0000000103c35adc _dispatch_workloop_worker_thread + 1324
23  libsystem_pthread.dylib             0x00000001b4d4af88 _pthread_wqthread + 276
24  libsystem_pthread.dylib             0x00000001b4d4dad4 start_wqthread + 8
2020-01-07 15:04:30.048897+0800 SimpleCam[11292:2714475] Can't end BackgroundTask: no background task exists with identifier 2 (0x2), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by lmf12** [comment]
GPUImage 的锅，目前来看应该不影响运行。
